.TH MPS 1 "May 2013" "MPlayerShell 0.9" "MPlayerShell Manual"
.SH NAME
.B mps
-- an improved visual experience for MPlayer on OS X
.SH SYNOPSIS
.B mps
[
.I mplayer arguments
]...

MPS_MPLAYER=/path/to/mplayer
.B mps
[
.I mplayer arguments
]...
.SH DESCRIPTION
.B MPlayerShell
is an improved visual experience for MPlayer on OS X, launching
.I mplayer
or
.I mplayer2
as a background process, capturing its output, and presenting a whole new application user interface. Its command line interface is essentially identical to MPlayer.

MPlayerShell also adds explicit menu commands for full-screen and float-on-top modes. Those new menu commands, as well as those for window sizing, are more consistent in appearance and behavior with the standard QuickTime Player application than with MPlayer.

However, full-screen mode in MPlayerShell doesn't use the animated transition behavior introduced in OS X Lion. It's "instant on" and similar to the mode built into MPlayer itself.

When MPlayerShell launches MPlayer, it's configured to use a larger cache and leverage multiple processor cores for more threads. This significantly improves performance for Blu-ray Disc-sized video. But even this sensible extra configuration can always be overridden at the command line.

As long as MPlayerShell is the frontmost application, all the standard MPlayer keyboard shortcuts work even if only audio is playing.

Mac OS X Snow Leopard (version 10.6) or later is required to run MPlayerShell.
.SH OPTIONS
.B MPlayerShell
takes almost all the same options as MPlayer, but there are a few important exceptions:
.TP
.B -
Not allowed because MPlayerShell launches MPlayer in "slave" mode and uses STDIN to send commands to MPlayer.
.TP
.B -vo
Not allowed because MPlayerShell must use a specific video output driver with certain parameters to capture video from MPlayer.
.TP
.B -idle
Ignored because MPlayerShell is the process controlling MPlayer.
.TP
.B -rootwin
Not implemented because it's not particularly useful in MPlayerShell.
.SH EXIT STATUS
.B MPlayerShell
returns as status whatever MPlayer itself returns when it exits in the background.
.SH ENVIRONMENT
.B MPlayerShell
first examines the
.B MPS_MPLAYER
environment variable for the location of
.IR mplayer .
This allows using
.I mplayer2
or other
.I mplayer
executables elsewhere in the file system. If the
.B MPS_MPLAYER
environment variable is undefined or empty, MPlayerShell searches the directories in the
.B PATH
environment variable for
.IR mplayer .
.SH SEE ALSO
.IR mplayer (1),
.IR mplayer2 (1)
.SH COPYRIGHT
Copyright (c) 2013 Don Melton
